### ISSUE TITLE
Saving vault location in settings throws error

### ISSUE THREAD

**Issue by philippgerard** [mikebarkmin/ulauncher-obsidian#1]
Message: 'com.github.mikebarkmin.ulauncher-obsidian'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3.9/site-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3.9/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3.9/site-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.mikebarkmin.ulauncher-obsidian'

```

**Comment by hhyurdagul** [comment]
I have exactly the same issue.

**Comment by mikebarkmin** [comment]
I am not sure what is coursing this error. Do you have other extensions installed? Do they work?

**Comment by hhyurdagul** [comment]
After a reboot it seems to work but the initial saving process was giving errors.

I dont know how but it is working now.

**Comment by mikebarkmin** [comment]
I have experienced the same with other extensions as well. I do not know if I as an extension developer need to do something different or if ulauncher has a bug.
