### ISSUE TITLE
Extension crashes instantly after install

### ISSUE THREAD

**Issue by argenos** [mikebarkmin/ulauncher-obsidian#7]
Message: 'com.github.mikebarkmin.ulauncher-obsidian'
Error Name: UnhandledError
Type: KeyError

Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 198, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 444, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.mikebarkmin.ulauncher-obsidian'

```

**Comment by mikebarkmin** [comment]
This is probably an issue with Ulauncher https://github.com/Ulauncher/Ulauncher/issues/763

**Comment by argenos** [comment]
Am I missing any dependencies as suggested in that issue?

**Comment by argenos** [comment]
I actually tried the suggestion there of installing pytz, but I already had that on my system. Any other clue as to what might be missing? The follow up issue seems to be also about dependencies: https://github.com/Ulauncher/Ulauncher/issues/767
